version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: integrador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=integrador
      - DB_USER=postgres
      - DB_PASSWORD=password
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=admin123
      - SECRET_KEY=desenvolvimento_secret_key
      - CLIENT_TABLE=integrador_cliente01
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
